Repository ShunFurusawa/Frisbee, pull requests merged in 2024-12, with the labels that each got.

#52 視点の回転＋補助線の回転最適化＋補助線の角度がおかしくなるバグ修正
  Frisbee/Assets/Prefabs/Frisbee.prefab
  Frisbee/Assets/Prefabs/[BuildingBlock] Camera Rig.prefab
  Frisbee/Assets/Scripts/Furusawa/CameraRotate.cs
  Frisbee/Assets/Scripts/Furusawa/CameraRotate.cs.meta
  Frisbee/Assets/Scripts/Furusawa/GameManager.cs
  Frisbee/Assets/Scripts/Furusawa/LineRotate.cs
Labels: bug, good first issue, program

#53 めり込みバグ修正
  Frisbee/Assets/Prefabs/Frisbee.prefab
  Frisbee/Assets/Prefabs/[BuildingBlock] Camera Rig.prefab
  Frisbee/Assets/Scenes/Test/test_SInking.unity
  Frisbee/Assets/Scenes/Test/test_SInking.unity.meta
  Frisbee/Assets/Scripts/Furusawa/SinkingFix.cs
Labels: bug, help wanted, program

#56 松明消えたので復活
  .idea/.idea.Frisbee.dir/.idea/workspace.xml
  Frisbee/Assets/Prefabs/Torch.prefab
  Frisbee/Assets/Prefabs/Torch.prefab.meta
  Frisbee/Assets/Scenes/Union.unity
Labels: bug

#57 Bgm attach
  Frisbee/Assets/Oculus/OculusProjectConfig.asset
  Frisbee/Assets/Scenes/Furusawa.unity
  Frisbee/Assets/sound.meta
  Frisbee/Assets/sound/BGM.meta
  Frisbee/Assets/sound/BGM/砂のダンジョン.wav
  Frisbee/Assets/sound/BGM/砂のダンジョン.wav.meta
  Frisbee/Assets/sound/SE.meta
  Frisbee/Assets/sound/SE/高速移動.wav
  Frisbee/Assets/sound/SE/高速移動.wav.meta
Labels: planer

#61 各種音実装
  Frisbee/Assets/Contents/Materials/Red.mat
  Frisbee/Assets/Prefabs/System/SoundManager.prefab
  Frisbee/Assets/Scenes/Test/test_SInking.unity
  Frisbee/Assets/Scripts/Furusawa/AfterThrow.cs
  Frisbee/Assets/Scripts/Furusawa/GameManager.cs
  Frisbee/Assets/Scripts/Furusawa/Reflection.cs
  Frisbee/Assets/Scripts/Furusawa/RespawnArea.cs
  Frisbee/Assets/Scripts/Furusawa/SoundManager.cs
  Frisbee/Assets/Scripts/Furusawa/SoundTest.cs
  Frisbee/Assets/Scripts/Furusawa/Throw Frisbee.cs
  Frisbee/Assets/Sounds.meta
  Frisbee/Assets/Sounds/BGM.meta
  Frisbee/Assets/Sounds/BGM/焚き火ループ.wav
  Frisbee/Assets/Sounds/BGM/焚き火ループ.wav.meta
  Frisbee/Assets/Sounds/BGM/砂のダンジョン.wav
  Frisbee/Assets/Sounds/BGM/砂のダンジョン.wav.meta
  Frisbee/Assets/Sounds/SE.meta
  Frisbee/Assets/Sounds/SE/Catch.wav
  Frisbee/Assets/Sounds/SE/Catch.wav.meta
  Frisbee/Assets/Sounds/SE/Fail.wav
  Frisbee/Assets/Sounds/SE/Fail.wav.meta
  Frisbee/Assets/Sounds/SE/Ready.wav
  Frisbee/Assets/Sounds/SE/Ready.wav.meta
  Frisbee/Assets/Sounds/SE/Reflect.wav
  Frisbee/Assets/Sounds/SE/Reflect.wav.meta
  Frisbee/Assets/Sounds/SE/Respawn.wav
  Frisbee/Assets/Sounds/SE/Respawn.wav.meta
  Frisbee/Assets/Sounds/SE/Return.wav
  Frisbee/Assets/Sounds/SE/Return.wav.meta
  Frisbee/Assets/Sounds/SE/TP.mp3
  Frisbee/Assets/Sounds/SE/TP.mp3.meta
  Frisbee/Assets/Sounds/SE/Throw.wav
  Frisbee/Assets/Sounds/SE/Throw.wav.meta
  Frisbee/Assets/Sounds/SE/Throw2.wav
  Frisbee/Assets/Sounds/SE/Throw2.wav.meta
Labels: program
